# Generated by Django 4.2.4 on 2023-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectimg')),
                ('Project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Title', models.CharField(max_length=50)),
                ('First_Service_Image', models.ImageField(upload_to='servimg1')),
                ('First_Service_Content', models.TextField(max_length=2000)),
                ('Service_Subtitle', models.CharField(max_length=200)),
                ('Second_Service_Content', models.TextField(max_length=2000)),
                ('Second_Service_Image', models.ImageField(upload_to='servimg2')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliderimg')),
                ('title', models.CharField(max_length=150)),
                ('Content', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Testomonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testmoimg')),
                ('clint_coments', models.TextField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.TextField(max_length=100)),
            ],
        ),
    ]
